# Generated by Django 4.2.30 on 2026-04-24 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_message_file_message_file_name_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
