# Generated by Django 4.2.29 on 2026-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_blocked_users_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url_42',
            field=models.URLField(blank=True, null=True),
        ),
    ]
